//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//


package com.auth.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for Bios complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bios">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Bio" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Bio"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)        //This Class Used For Conversion POJOToXML and XMLToPOJO
@XmlType(name = "Bios", propOrder =         // Bios is Basically Tag Name (i.e. name="Bios") and  propOrder="bio means that Subelement"
{
    "bio"
})
public class Bios {

    @XmlElement(name = "Bio")
    protected List<Bio> bio;

    /**
     * Gets the value of the bio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bio }
     * 
     * 
     */
    public List<Bio> getBio() {
        if (bio == null) {
            bio = new ArrayList<Bio>();
        }
        return this.bio;
    }

}
