//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//


package com.auth.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Demo" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Demo" minOccurs="0"/>
 *         &lt;element name="Bios" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Bios" minOccurs="0"/>
 *         &lt;element name="Pv" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Pv" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ver" type="{http://www.w3.org/2001/XMLSchema}string" default="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

/*1.This class is used for Conversion of
 * i)POJO To XML
 * ii)XML To POJO
 *2.XML Element Map with class variables.
 *3.Generating Setter and getter method.
 * */


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"bios","pv"
})
@XmlRootElement(name = "Pid", namespace="http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0")
public class Pid {

  /* @XmlElement(name = "Demo")
    protected Demo demo;*/
    @XmlElement(name = "Bios")
    protected Bios bios;
    @XmlElement(name = "Pv")
    protected Pv pv;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String ts;
    @XmlAttribute
    protected String ver;
   

    /**
     * Gets the value of the demo property.
     * 
     * @return
     *     possible object is
     *     {@link Demo }
     *     
     */
  

    /**
     * Gets the value of the pv property.
     * 
     * @return
     *     possible object is
     *     {@link Pv }
     *     
     */
    public Pv getPv() {
        return pv;
    }

    /**
     * Sets the value of the pv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pv }
     *     
     */
    public void setPv(Pv value) {
        this.pv = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        if (ver == null) {
            return "1.0";
        } else {
            return ver;
        }
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

	public Bios getBios() {
		return bios;
	}

	public void setBios(Bios bios) {
		this.bios = bios;
	}

}
