//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.03 at 04:17:43 PM IST 
//


package com.auth.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Resp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Resp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="kycRes" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Resp", propOrder = {
    "kycRes"
})
@XmlRootElement(name = "Resp") 

															/* Note:
																		1.Resp  class is used for Getting to Response ekycServer
																		2.Here we are done Marshalling and Unmarshalling  i.e. 
   																			a.Pojo to xml
   																			b.xml to pojo
																		3.Acessing that response using @XmlAttribute
																		4.Added Setter method and Getter Method
																		5.kycResp is propOrder means Subelement */
public class Resp {                                            
	
	/*@XmlElement
    protected byte[] kycRes;*/
	@XmlElement(name="KycRes")
    protected KycRes kycRes;
    @XmlAttribute
    protected String status;
    @XmlAttribute
    protected String ko;
    @XmlAttribute
    protected YesNoType ret;
    @XmlAttribute
    protected String code;
    @XmlAttribute
    protected String txn; 
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ts;
    @XmlAttribute
    protected String err;
    

    /**
     * Gets the value of the kycRes property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
   

    /**
     * Sets the value of the kycRes property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    public KycRes getKycRes() {
		return kycRes;
	}

	public void setKycRes(KycRes kycRes) {
		this.kycRes = kycRes;
	}

	/**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

	public String getKo() {
		return ko;
	}

	public void setKo(String ko) {
		this.ko = ko;
	}

	public YesNoType getRet() {
		return ret;
	}

	public void setRet(YesNoType ret) {
		this.ret = ret;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTxn() {
		return txn;
	}

	public void setTxn(String txn) {
		this.txn = txn;
	}

	public XMLGregorianCalendar getTs() {
		return ts;
	}

	public void setTs(XMLGregorianCalendar ts) {
		this.ts = ts;
	}

	public String getErr() {
		return err;
	}

	public void setErr(String err) {
		this.err = err;
	}
    
    

}
