//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 04:38:08 PM IST 
//


package com.auth.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for Uses complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Uses">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pi" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *       &lt;attribute name="pa" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *       &lt;attribute name="pfa" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *       &lt;attribute name="bio" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *       &lt;attribute name="bt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pin" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *       &lt;attribute name="otp" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}UsesFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


/*1.This class is used for Conversion of
 * i)POJO To XML
 * ii)XML To POJO
 *2.XML Element Map with class variables.
 *3.Generating Setter and getter method.
 * */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Uses")
public class Uses {

    @XmlAttribute(required = true)
    protected UsesFlag pi;
    @XmlAttribute(required = true)
    protected UsesFlag pa;
    @XmlAttribute(required = true)
    protected UsesFlag pfa;
    @XmlAttribute(required = true)
    protected UsesFlag bio;
    @XmlAttribute
    protected String bt;
    @XmlAttribute(required = true)
    protected UsesFlag pin;
    @XmlAttribute(required = true)
    protected UsesFlag otp;

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getPi() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setPi(UsesFlag value) {
        this.pi = value;
    }

    /**
     * Gets the value of the pa property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getPa() {
        return pa;
    }

    /**
     * Sets the value of the pa property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setPa(UsesFlag value) {
        this.pa = value;
    }

    /**
     * Gets the value of the pfa property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getPfa() {
        return pfa;
    }

    /**
     * Sets the value of the pfa property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setPfa(UsesFlag value) {
        this.pfa = value;
    }

    /**
     * Gets the value of the bio property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getBio() {
        return bio;
    }

    /**
     * Sets the value of the bio property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setBio(UsesFlag value) {
        this.bio = value;
    }

    /**
     * Gets the value of the bt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBt() {
        return bt;
    }

    /**
     * Sets the value of the bt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBt(String value) {
        this.bt = value;
    }

    /**
     * Gets the value of the pin property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getPin() {
        return pin;
    }

    /**
     * Sets the value of the pin property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setPin(UsesFlag value) {
        this.pin = value;
    }

    /**
     * Gets the value of the otp property.
     * 
     * @return
     *     possible object is
     *     {@link UsesFlag }
     *     
     */
    public UsesFlag getOtp() {
        return otp;
    }

    /**
     * Sets the value of the otp property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesFlag }
     *     
     */
    public void setOtp(UsesFlag value) {
        this.otp = value;
    }

}
